version: '3.3'

services:
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - net
  spark-jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "4040:4040"
      - "4041-4050:4041-4050"
    volumes:
      - ./benchmark:/benchmark
    networks:
      - net


networks:
  net:
    driver: bridge
